---
title: "Case Study 2"
author: "Aaron Cattley"
date: "4/9/2019"
output: html_document
---
#Introduction
  #This is an analysis of employee data to determine the strongest predictors of attrition in employees.  We've also done two predictive analysis to predict both attrition and salary.
  #Youtube link - https://youtu.be/RvA2pA9NTYs
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE, echo=TRUE}
library(dplyr)
library(tidyr)
library(nlme)
library(caret)
library(class)
library(plyr)
library(dygraphs)
library(fpp2)
library(randomForest)
library(e1071)
library(ggplot2)
library(corrplot)
library(naivebayes)
library(MASS)
library(kableExtra)
```

#Data import and cleaning
```{r, echo=TRUE}
#Read in the data
TMdata <- read.csv('C:/Users/acattley/Documents/MSDS-6306-Doing-Data-Science/UNIT 14/CaseStudy2-data.csv', header = T, stringsAsFactors = T)
TMattr <- read.csv('C:/Users/acattley/Documents/MSDS-6306-Doing-Data-Science/UNIT 14/CaseStudy2Validation No Attrition.csv', header = T, stringsAsFactors = T)
TMsalary <- read.csv('C:/Users/acattley/Documents/MSDS-6306-Doing-Data-Science/UNIT 14/CaseStudy2Validation No Salary.csv', header = T, stringsAsFactors = T)

#Sanity checks, NA check
str(TMdata)
any(is.na(TMdata))
summary(TMdata)

#Based on the overview of the data, there are a few columns that are unlikely to impact this analysis.
#The columns are: Over18, EmployeeCnt, EmployeeNum, StandardHrs
TMdata <- subset(TMdata, select = -c(Over18, EmployeeCount, EmployeeNumber, StandardHours, Rand))

#Prep work for correlations
TMdata_num <- TMdata[, sapply(TMdata, is.numeric)]
TMdata_corr <- round(cor(TMdata_num),2)
```
#Exploration of Data
  ##Looking at the key topics of this study: Attrition and Salary
```{r, echo=TRUE}
#Quick plots of the two main topics
#Attrition
table(TMdata$Attrition)
barplot(prop.table(table(TMdata$Attrition)), main = "Attrition Breakdown")

#Salary
hist(TMdata$MonthlyIncome,
     main="Income Distribution", 
     xlab="Income", 
     col="blue",
     las=1, 
     breaks=10)

#From an overview, it seems as though ~80% of employees are not experiencing attrition.  Moreover the Salary distribution is right skewed, but the sample size should be sufficient to be robust to non normality.

#We'll now plot some additional classifications to get a sense of how the groups of employees are distributed.
hist(TMdata$Age,
     main="Age Distribution", 
     xlab="Age", 
     col="red",
     las=1, 
     breaks=10)

#Age distribution is fairly normal for this data set.


#Plot of OverTime vs Attrtion
ggplot(TMdata,aes(x=OverTime,fill = Attrition))+geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge")+ggtitle("Attrition based on Overtime factors") + labs(x = "OverTime", y = "Percentage")

#Percentages tabled for OT vs A.
TableOTA <- xtabs(~OverTime+Attrition, data = TMdata)
tabl1 <- data.frame(ftable(TableOTA))
percenta<- tabl1[3,3]/(tabl1[3,3]+tabl1[1,3])*100
percentb<- tabl1[4,3]/(tabl1[4,3]+tabl1[2,3])*100
Attrition_Percent <-round(c(0,0,percenta,percentb),2)
dfa <- data.frame(tabl1,Attrition_Percent)
dfa

#Gender versus Attrition
ggplot(TMdata,aes(x=Gender,fill = Attrition))+geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge")+ggtitle("Attrition based on Gender") + labs(x = "Gender", y = "Percentage")

#60% males and 40% females

TableGA <- xtabs(~Gender+Attrition, data = TMdata)
tablga <- data.frame(ftable(TableGA))
percentf<- tablga[3,3]/(tablga[3,3]+tablga[1,3])*100
percentm<- tablga[4,3]/(tablga[4,3]+tablga[2,3])*100
Attrition_PercentGA <-round(c(0,0,percentf,percentm),2)
dfga <- data.frame(tablga,Attrition_PercentGA)
dfga

#There does not seem to be a trend of one gender experiencing more attrtion then the other so gender is most likely not a factor.

#Distribution of Job Involvement and their percentages
ggplot(TMdata,aes(x=JobInvolvement,fill = Attrition))+geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge")+ggtitle("Attrition based on Job Involvement factors") +labs(x = "Job Involvement level", y = "Percentage")
mytable3 <- xtabs(~JobInvolvement+Attrition, data = TMdata)
tabl3<- data.frame(ftable(mytable3))
percent31<- tabl3[5,3]/(tabl3[5,3]+tabl3[1,3])*100
percent32<- tabl3[6,3]/(tabl3[6,3]+tabl3[2,3])*100
percent33<- tabl3[7,3]/(tabl3[7,3]+tabl3[3,3])*100
percent34<- tabl3[8,3]/(tabl3[8,3]+tabl3[4,3])*100
Attrition_Percent <-round(c(0,0,0,0,percent31,percent32,percent33,percent34),2)
df3 <- data.frame(tabl3,Attrition_Percent)
df3

#Distribution of employees Stock Options and their percentages
ggplot(TMdata,aes(x=StockOptionLevel,fill = Attrition))+geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge")+ggtitle("Attrition based on Stock Option factors") +labs(x = "Stock Option Level", y = "Percentage")
mytable4 <- xtabs(~StockOptionLevel+Attrition, data = TMdata)
tabl4<- data.frame(ftable(mytable4))
percent41<- tabl4[5,3]/(tabl4[5,3]+tabl4[1,3])*100
percent42<- tabl4[6,3]/(tabl4[6,3]+tabl4[2,3])*100
percent43<- tabl4[7,3]/(tabl4[3,3]+tabl4[7,3])*100
percent44<- tabl4[8,3]/(tabl4[8,3]+tabl4[4,3])*100
Attrition_Percent <-round(c(0,0,0,0,percent41,percent42,percent43,percent44),2)
df4 <- data.frame(tabl4,Attrition_Percent)
df4

TableWLBA <- xtabs(~WorkLifeBalance+Attrition, data = TMdata)
tabl2 <- data.frame(ftable(TableWLBA))
percent1<- tabl2[5,3]/(tabl2[1,3]+tabl2[5,3])*100
percent2<- tabl2[6,3]/(tabl2[2,3]+tabl2[6,3])*100
percent3<- tabl2[7,3]/(tabl2[3,3]+tabl2[7,3])*100
percent4<- tabl2[8,3]/(tabl2[4,3]+tabl2[8,3])*100
Attrition_Percent2 <-round(c(0,0,0,0,percent1,percent2,percent3,percent4),2)
dfb <- data.frame(tabl2,Attrition_Percent2)
dfb

#Attrition by Age
ggplot(TMdata,aes(x = Age,fill = Attrition)) +
  geom_histogram(aes(y = 100*(..count..)/sum(..count..)), position = "dodge", binwidth = 10) + 
  ggtitle("Age vs Attrition") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))

#WLB vs. OT
ggplot(TMdata,aes(x = WorkLifeBalance,fill = OverTime)) +
  geom_histogram(aes(y = 100*(..count..)/sum(..count..)), position = "dodge") + 
  ggtitle("Work Life Balance vs Attrition") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))

#Younger people seem to be more prone to attrition based on this chart

ggplot(TMdata, aes(x=Age, y=MonthlyIncome, color = Attrition)) + geom_point (size = 2, shape = 18) + geom_smooth(method = lm, linetype = "dashed", color = "red", fill = "blue") + labs(y = "Monthly Income") + ggtitle("Age vs. Monthly income by Attrition")

#I've taken the Age component a step further and created a scatterplot with Age and Monthly Income, colored by Attrtion.  A majority of Attrtion cases seem to be in lower income young people.

#Travel vs. Attrition
ggplot(TMdata,aes(x = BusinessTravel,fill = Attrition)) +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge") + 
  ggtitle("Business Travel vs Attrition - Count") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))
#No major indications that travel might contribute significantly to attrition.

#Job Role vs. Attrition
ggplot(TMdata,aes(x = JobRole, fill = Attrition)) +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)), position = "dodge") + 
  ggtitle("Job Role vs Attrition") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))


#Looking at employees Education Field by their role, to determine if employees are in roles they went to school for.
ggplot(TMdata,aes(x = EducationField,fill = JobRole)) +
  geom_bar(aes(y = 100*(..count..)/sum(..count..)),position = "dodge") +
  ggtitle("Education Field distrubuted by Job Role") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))

#Monthly income by attrtion
ggplot(TMdata,aes(x = MonthlyIncome,fill = Attrition)) +
  geom_histogram(aes(y = 100*(..count..)/sum(..count..)),position = "dodge", bins = 10) + 
  ggtitle("Monthly Income vs Attrition") + labs(y="Percentage") +
  theme(plot.title = element_text(hjust = 0.5))

#Heatmap
corrplot.mixed(TMdata_corr, order="FPC", upper = "shade", lower = "number", tl.pos = "lt", tl.srt=45)

#The following groups seem to have high enough correlation they warrant removal from the analysis:
# TotalWorkingYears correlates with JobLevel and Age, along with several others
# JobLevel correlates with MonthlyIncome among others
# YearsInCurrentRole/YearsAtCompany/YearsWithCurrManager - All 3 correlate with on another, YearsCurrentRole will be removed.
# Age/TotalWorkingYears - 0.65
# There are others, but I would like to test them first before removing, such as YearsWithCurrManager.  A good manager can really make a difference in how employees feel towards their job.
# For this study, I am removing YearsAtCompany and YearsCurrentRole for the following reasons:
#   Someone who just changed roles could move from very unhappy to happy or vice versa
#   A long time employee could have gone through ups and downs, love stability, or be a tucked in the corner kind of worker
# Performance rating and Salary hike correlate strongly.  Money typically is a short term, low impact factor on attrition.  I will work with each variable in the model to see how the model output looks.
```

```{r, echo=TRUE}
#Salary EDA
#Jobe Role vs. Monthly Income
ggplot(TMdata, aes(x=JobRole, y=MonthlyIncome)) + geom_boxplot (size = 2, shape = 18) + labs(y = "Monthly Income") + ggtitle("Job Role vs. Monthly Income")

#Total Working Years vs. Monthly Income
ggplot(TMdata, aes(x=TotalWorkingYears, y=MonthlyIncome)) + geom_point (size = 2, shape = 18) + geom_smooth(method = lm, linetype = "dashed", color = "red", fill = "blue") + labs(y = "Monthly Income") + ggtitle("Total Working Years vs. Monthly Income")

#Education Field vs. Monthly Income
ggplot(TMdata, aes(x=EducationField, y=MonthlyIncome)) + geom_boxplot (size = 2, shape = 18) + ggtitle("Education Field vs. Monthly Income")

#Job Level vs. Monthly Income.
ggplot(TMdata, aes(x=JobLevel, y=MonthlyIncome, group = JobLevel)) + geom_boxplot (size = 2, shape = 18) + ggtitle("Job Level vs. Monthly Income")

```



```{r, echo=TRUE}
#Building a model
#Random Forest
TMdata.rf <- randomForest(Attrition~., data=TMdata, ntree = 1000, importance = TRUE)

#Checking importance
importance(TMdata.rf)

#Plot of important variables
varImpPlot(TMdata.rf, main='Random Tree Variable Importance')

#Naive Bayes Model
TMdata.nb=naiveBayes(Attrition~ MonthlyIncome + DailyRate + JobSatisfaction + Age + Education + EnvironmentSatisfaction +   PerformanceRating + YearsSinceLastPromotion + YearsWithCurrManager + YearsAtCompany + YearsInCurrentRole + WorkLifeBalance +  JobRole + JobInvolvement + JobLevel + OverTime + TotalWorkingYears + StockOptionLevel + MaritalStatus + RelationshipSatisfaction + PercentSalaryHike, data=TMdata)

#Prediction on the dataset
TMpreds=predict(TMdata.nb,TMdata)

#Confusion matrix to check accuracy
confusionMatrix(table(TMpreds,TMdata$Attrition))
cMatrix<-table(TMpreds, TMdata$Attrition)
plot(cMatrix, col="blue", ylab="Actual", xlab="Predicted", main='Naive Bayes Confusion Matrix')

#Add predicted values
TMpreds2=predict(TMdata.nb,TMattr)
TMattr$PredictedAttrition <- TMpreds2
TMAtrPred <- data.frame(TMattr$ID, TMattr$PredictedAttrition)
colnames(TMAtrPred) <- c("ID", "Predicted Attrition")

#Write to csv
write.csv(TMAtrPred, "Case Study 2 Predicted Attrition.csv")
```

```{r, echo=TRUE}
#Salary
#Random Forest to determine important variables
TMdata.rf2 <- randomForest(MonthlyIncome ~ ., data=TMdata, ntree = 1000, importance = TRUE)

#Checking importance
importance(TMdata.rf)

#Plot of important variables
varImpPlot(TMdata.rf, main='Random Tree Variable Importance')

#LM to determine model efficiency
TMdata.lm2 <- lm(MonthlyIncome ~ DailyRate + JobSatisfaction + Age + EnvironmentSatisfaction + YearsSinceLastPromotion + YearsWithCurrManager + YearsAtCompany + YearsInCurrentRole + WorkLifeBalance + JobRole + JobInvolvement + JobLevel + OverTime + TotalWorkingYears + StockOptionLevel + MaritalStatus + PercentSalaryHike, data=TMdata)

summary(TMdata.lm2)

RMSEfit <- sqrt(mean(resid(TMdata.lm2)^2))
RMSEfit

#Set training and test
samplesize = 870
train_perc = .6

#Texas training
train_indices = sample(seq(1,samplesize,length = samplesize),round(train_perc*samplesize))
TMtrain = TMdata[train_indices,]
TMtest= TMdata[-train_indices,]

#Train and test
fitTrain1 = lm(MonthlyIncome ~ DailyRate + JobSatisfaction + Age + EnvironmentSatisfaction + YearsSinceLastPromotion + YearsWithCurrManager + YearsAtCompany + YearsInCurrentRole + WorkLifeBalance + JobRole + JobInvolvement + JobLevel + OverTime + TotalWorkingYears + StockOptionLevel + MaritalStatus + PercentSalaryHike, data=TMdata)

#New data frame with predicted values
predsTest1 = predict(fitTrain1, newdata = TMsalary)
TMsalary$PredictedSalary <- predsTest1
TMSalPred <- data.frame(TMsalary$ID, TMsalary$PredictedSalary)
colnames(TMSalPred) <- c("ID", "Predicted Salary")

#Write to csv
write.csv(TMSalPred, "Case Study 2 Predicted Salaries.csv")
```
